export const STORY_STEPS = [
	{
		index: 0,
		title: 'Yerevan Parking Supply',
		subtitle: 'A spatial inventory of on-street and off-street parking across the city',
		isIntro: true,
		center: [44.5036, 40.1735],
		zoom: 11.8,
		pitch: 0,
		bearing: 0,
		showLines: false,
		showAreas: false,
		showCorridors: false,
		showLandmarks: false,
		legendVisible: false,
	},
	{
		index: 1,
		title: 'Study Corridors',
		subtitle: 'Three primary routes of analysis',
		center: [44.505, 40.165],
		zoom: 12.8,
		pitch: 20,
		bearing: 0,
		showLines: false,
		showAreas: false,
		showCorridors: true,
		showLandmarks: false,
		colorMode: 'default',
		legendVisible: true,
		legendLayers: [
			{ id: 'corridor-1', label: 'Corridor 01', color: '#ffaa00' },
			{ id: 'corridor-2', label: 'Corridor 02', color: '#55aaff' },
			{ id: 'corridor-3', label: 'Corridor 03', color: '#00aa00' },
		],
		description: 'The parking survey was structured around three major corridors spanning north-south and east-west through the city, capturing the diversity of parking conditions.',
	},
	{
		index: 2,
		title: 'The Full Picture',
		subtitle: 'Every surveyed parking segment and lot',
		center: [44.5036, 40.1735],
		zoom: 12.5,
		pitch: 30,
		bearing: -10,
		showLines: true,
		showAreas: true,
		showCorridors: false,
		showLandmarks: true,
		colorMode: 'default',
		legendVisible: true,
		legendLayers: [
			{ id: 'on-street', label: 'On-Street Parking', color: '#42a5f5', layerId: 'parking-lines' },
			{ id: 'off-street', label: 'Off-Street / Yards', color: '#7c4dff', layerId: 'parking-areas-fill' },
			{ id: 'landmarks', label: 'Landmarks', color: '#FFC107', layerId: 'landmarks-points' },
		],
		stats: [
			{ value: 11217, label: 'Total Spaces', color: '#00CED1' },
			{ value: 728, label: 'Street Segments', color: '#42a5f5' },
			{ value: 266, label: 'Off-Street Areas', color: '#7c4dff' },
		],
		description: 'A comprehensive survey of parking supply across Yerevan, covering both on-street curbside parking and off-street yards and lots.',
	},
	{
		index: 3,
		title: 'On-Street Parking',
		subtitle: 'Curbside segments along city streets',
		center: [44.51, 40.177],
		zoom: 14,
		pitch: 40,
		bearing: 20,
		showLines: true,
		showAreas: false,
		showCorridors: false,
		showLandmarks: false,
		colorMode: 'default',
		legendVisible: true,
		legendLayers: [
			{ id: 'on-street', label: 'On-Street Segments', color: '#42a5f5', layerId: 'parking-lines' },
		],
		stats: [
			{ value: 4044, label: 'On-Street Spaces', color: '#42a5f5' },
			{ value: 2952, label: 'Curbside', color: '#64B5F6' },
			{ value: 850, label: 'Pocket Parking', color: '#1E88E5' },
		],
		description: 'On-street parking accounts for 4,044 spaces across 728 surveyed segments. Most are curbside parallel spots along major and secondary streets.',
	},
	{
		index: 4,
		title: 'Off-Street & Yard Parking',
		subtitle: 'Residential yards and surface lots',
		center: [44.505, 40.178],
		zoom: 14.2,
		pitch: 45,
		bearing: -15,
		showLines: false,
		showAreas: true,
		showCorridors: false,
		showLandmarks: false,
		colorMode: 'default',
		legendVisible: true,
		legendLayers: [
			{ id: 'off-street', label: 'Off-Street Areas', color: '#7c4dff', layerId: 'parking-areas-fill' },
		],
		stats: [
			{ value: 7173, label: 'Off-Street Spaces', color: '#7c4dff' },
			{ value: 266, label: 'Areas Surveyed', color: '#B388FF' },
		],
		description: 'Off-street areas hold the majority of Yerevan\'s parking supply — 7,173 spaces across 266 surveyed yards and lots, mostly in residential courtyards.',
	},
	{
		index: 5,
		title: 'Parking Methods',
		subtitle: 'How vehicles are arranged',
		center: [44.513, 40.175],
		zoom: 14.5,
		pitch: 35,
		bearing: 10,
		showLines: true,
		showAreas: false,
		showCorridors: false,
		showLandmarks: false,
		colorMode: 'method',
		legendVisible: true,
		legendLayers: [
			{ id: 'parallel', label: 'Parallel (2,825)', color: '#4CAF50' },
			{ id: 'angle-90', label: '90-Degree (665)', color: '#FF9800' },
			{ id: 'angle-45', label: '45-Degree (123)', color: '#E91E63' },
		],
		stats: [
			{ value: 2825, label: 'Parallel', color: '#4CAF50' },
			{ value: 665, label: '90-Degree', color: '#FF9800' },
			{ value: 123, label: '45-Degree', color: '#E91E63' },
		],
		description: 'Parallel parking dominates Yerevan\'s streets, accounting for 78% of surveyed on-street spaces. Angled parking (90° and 45°) appears in pockets and set-back areas.',
	},
	{
		index: 6,
		title: 'Parking Signage',
		subtitle: 'Formal vs. informal parking',
		center: [44.512, 40.177],
		zoom: 14.2,
		pitch: 35,
		bearing: -5,
		showLines: true,
		showAreas: false,
		showCorridors: false,
		showLandmarks: false,
		colorMode: 'signage',
		legendVisible: true,
		legendLayers: [
			{ id: 'signed', label: 'With Signage (1,031)', color: '#4CAF50' },
			{ id: 'unsigned', label: 'No Signage (2,771)', color: '#EF5350' },
		],
		stats: [
			{ value: 1031, label: 'Signed Spaces', color: '#4CAF50' },
			{ value: 2771, label: 'Unsigned Spaces', color: '#EF5350' },
		],
		description: 'Only 27% of on-street parking spaces have formal signage. The majority of parking in Yerevan is informal — drivers park where convention allows, not where signs direct.',
	},
	{
		index: 7,
		title: 'Busiest Streets',
		subtitle: 'Where parking supply concentrates',
		center: [44.497, 40.17],
		zoom: 13.5,
		pitch: 40,
		bearing: 15,
		showLines: true,
		showAreas: true,
		showCorridors: false,
		showLandmarks: false,
		colorMode: 'default',
		legendVisible: true,
		legendLayers: [
			{ id: 'on-street', label: 'On-Street Parking', color: '#42a5f5', layerId: 'parking-lines' },
			{ id: 'off-street', label: 'Off-Street / Yards', color: '#7c4dff', layerId: 'parking-areas-fill' },
		],
		topStreets: [
			{ name: 'Arshakunyac', spaces: 1012, type: 'yard' },
			{ name: 'Komitas', spaces: 871, type: 'yard' },
			{ name: 'Bagratunyac', spaces: 695, type: 'yard' },
			{ name: 'Komitas', spaces: 507, type: 'street' },
			{ name: 'Rubinyan', spaces: 485, type: 'street' },
			{ name: 'Shiraz', spaces: 446, type: 'yard' },
			{ name: 'Sebastia', spaces: 442, type: 'yard' },
		],
		description: 'Arshakunyac Avenue leads with over 1,000 yard-parking spaces. Komitas Avenue has the highest combined supply — 507 on-street plus 871 in courtyards.',
	},
	{
		index: 8,
		title: 'Key Landmarks',
		subtitle: 'Major destinations with parking impact',
		center: [44.51, 40.19],
		zoom: 13,
		pitch: 25,
		bearing: 0,
		showLines: true,
		showAreas: true,
		showCorridors: false,
		showLandmarks: true,
		colorMode: 'default',
		legendVisible: true,
		legendLayers: [
			{ id: 'on-street', label: 'On-Street Parking', color: '#42a5f5', layerId: 'parking-lines' },
			{ id: 'off-street', label: 'Off-Street / Yards', color: '#7c4dff', layerId: 'parking-areas-fill' },
			{ id: 'landmarks', label: 'Landmarks', color: '#FFC107', layerId: 'landmarks-points' },
		],
		description: 'Major malls and institutions — Mega Mall, Yerevan City Mall, the Sport/Concert Complex — generate significant parking demand, each with their own off-street facilities.',
	},
];
